FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# wait-for-it.sh 복사 및 실행 권한 부여
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# 앱 소스 전체 복사
COPY . .

EXPOSE 8000


CMD /bin/sh -c "/wait-for-it.sh db:5432 -- echo 'Database is up' && \
    alembic upgrade head && \
    uvicorn app.main:app --host=0.0.0.0 --port=8000 --reload"
